name: CI on Push and Pull Request

on: [push, pull_request]

jobs:
  Practice:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Show what's in the directory
      run: |
        ls
    - name: Show what all is in the parent directory
      run: |
        cd ..
        ls
        
  Android:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Android
      run: |
        cd AwesomeApp
        nuget restore
        cd AwesomeApp.Android
        msbuild AwesomeApp.Android.csproj /verbosity:normal /t:PackageForAndroid /p:Configuration=Debug
    
    - name: App Center
      uses: wzieba/AppCenter-Github-Action@v1.0.0
      with:
        # App name followed by username e.g. wzieba/Sample-App
        appName: Ch-DemoOrg/demoapp
        # Upload token - you can get one from appcenter.ms/settings
        token: 373aa94633ee913428d314be9c137be70bc29dbe
        # Distribution group
        group: betatesters
        # Artefact to upload (.apk or .ipa)
        file: "**/com.companyname.AwesomeApp.apk"
        # Release notes visible on release page
        releaseNotes: "demo test"
        
  iOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: iOS
      run: |
        cd AwesomeApp
        nuget restore
        msbuild AwesomeApp.iOS/AwesomeApp.iOS.csproj /verbosity:normal /t:Rebuild /p:Platform=iPhoneSimulator /p:Configuration=Debug
